
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - 
      The host system is: Windows - 10.0.26100 - AMD64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/NSU/MyLabs/ADDED_LIBS/emsdk/upstream/emscripten/emcc.bat 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out.js"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out.wasm"
      
      The C compiler identification could not be found in:
        D:/NSU/MyLabs/GITLab/Petrov's GitLab/database-lab/back-end/cmake-build-debug/CMakeFiles/3.30.5/CompilerIdC/a.out.js
      
      The C compiler identification is Clang, found in:
        D:/NSU/MyLabs/GITLab/Petrov's GitLab/database-lab/back-end/cmake-build-debug/CMakeFiles/3.30.5/CompilerIdC/a.out.wasm
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/NSU/MyLabs/GITLab/Petrov's GitLab/database-lab/back-end/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-bqmh9o"
      binary: "D:/NSU/MyLabs/GITLab/Petrov's GitLab/database-lab/back-end/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-bqmh9o"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: " -s EXPORTED_FUNCTIONS=[_add_record_js,_print_all_js,_find_by_name_js,_delete_by_passengerId_js] -s EXPORTED_RUNTIME_METHODS=[cwrap] -s ENVIRONMENT=web"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/NSU/MyLabs/GITLab/Petrov's GitLab/database-lab/back-end/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-bqmh9o'
        
        Run Build Command(s): "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/ninja/win/x64/ninja.exe" -v cmTC_34f99
        [1/2] D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\emcc.bat   -v -MD -MT CMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_34f99.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -c "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeCCompilerABI.c"
         "D:/NSU/MyLabs/ADDED_LIBS/emsdk/upstream/bin\\clang.exe" -target wasm32-unknown-emscripten -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\cache\\sysroot -DEMSCRIPTEN -Xclang -iwithsysroot/include\\fakesdl -Xclang -iwithsysroot/include\\compat -v -MD -MT CMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_34f99.dir\\CMakeCCompilerABI.c.obj.d -oCMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -c "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeCCompilerABI.c"
        clang version 21.0.0git (https:/github.com/llvm/llvm-project 4775e6d9099467df9363e1a3cd5950cc3d2fde05)
        Target: wasm32-unknown-emscripten
        Thread model: posix
        InstalledDir: D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\bin
         (in-process)
         "D:\\\\NSU\\\\MyLabs\\\\ADDED_LIBS\\\\emsdk\\\\upstream\\\\bin\\\\clang.exe" -cc1 -triple wasm32-unknown-emscripten -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility=hidden -debugger-tuning=gdb "-fdebug-compilation-dir=D:\\\\NSU\\\\MyLabs\\\\GITLab\\\\Petrov's GitLab\\\\database-lab\\\\back-end\\\\cmake-build-debug\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-bqmh9o" -v "-fcoverage-compilation-dir=D:\\\\NSU\\\\MyLabs\\\\GITLab\\\\Petrov's GitLab\\\\database-lab\\\\back-end\\\\cmake-build-debug\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-bqmh9o" -resource-dir "D:\\\\NSU\\\\MyLabs\\\\ADDED_LIBS\\\\emsdk\\\\upstream\\\\lib\\\\clang\\\\21" -dependency-file "CMakeFiles\\\\cmTC_34f99.dir\\\\CMakeCCompilerABI.c.obj.d" -MT CMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -sys-header-deps -D EMSCRIPTEN -isysroot "D:\\\\NSU\\\\MyLabs\\\\ADDED_LIBS\\\\emsdk\\\\upstream\\\\emscripten\\\\cache\\\\sysroot" -internal-isystem "D:\\\\NSU\\\\MyLabs\\\\ADDED_LIBS\\\\emsdk\\\\upstream\\\\lib\\\\clang\\\\21\\\\include" -internal-isystem "D:\\\\NSU\\\\MyLabs\\\\ADDED_LIBS\\\\emsdk\\\\upstream\\\\emscripten\\\\cache\\\\sysroot/include/wasm32-emscripten" -internal-isystem "D:\\\\NSU\\\\MyLabs\\\\ADDED_LIBS\\\\emsdk\\\\upstream\\\\emscripten\\\\cache\\\\sysroot/include" -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fignore-exceptions "-iwithsysroot/include\\\\fakesdl" "-iwithsysroot/include\\\\compat" -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o CMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -x c "C:/Program Files (x86)/JetBrains/CLion 2024.3.5/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeCCompilerABI.c"
        clang -cc1 version 21.0.0git based upon LLVM 21.0.0git default target x86_64-pc-windows-msvc
        ignoring nonexistent directory "D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\cache\\sysroot/include/wasm32-emscripten"
        #include "..." search starts here:
        #include <...> search starts here:
         D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\cache\\sysroot/include\\fakesdl
         D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\cache\\sysroot/include\\compat\x0d
         D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\lib\\clang\\21\\include\x0d
         D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\cache\\sysroot/include\x0d
        End of search list.\x0d
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\emcc.bat  -s EXPORTED_FUNCTIONS=[_add_record_js,_print_all_js,_find_by_name_js,_delete_by_passengerId_js] -s EXPORTED_RUNTIME_METHODS=[cwrap] -s ENVIRONMENT=web -v CMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -o cmTC_34f99   && cd ."
        FAILED: cmTC_34f99 
        C:\\WINDOWS\\system32\\cmd.exe /C "cd . && D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\emcc.bat  -s EXPORTED_FUNCTIONS=[_add_record_js,_print_all_js,_find_by_name_js,_delete_by_passengerId_js] -s EXPORTED_RUNTIME_METHODS=[cwrap] -s ENVIRONMENT=web -v CMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -o cmTC_34f99   && cd ."
         "D:/NSU/MyLabs/ADDED_LIBS/emsdk/upstream/bin\\clang.exe" --version
        cache:INFO: generating system asset: symbol_lists/84867a371748950712caaa15a71c3d1d9ce882b7.json... (this will be cached in "D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\cache\\symbol_lists\\84867a371748950712caaa15a71c3d1d9ce882b7.json" for subsequent builds)
         "D:/NSU/MyLabs/ADDED_LIBS/emsdk/node/20.18.0_64bit/bin/node.exe" D:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\tools\\compiler.mjs - --symbols-only
        cache:INFO:  - ok
         "D:/NSU/MyLabs/ADDED_LIBS/emsdk/upstream/bin\\wasm-ld.exe" -o cmTC_34f99.wasm CMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -LD:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\cache\\sysroot\\lib\\wasm32-emscripten -LD:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\src\\lib -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc-debug -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\\Users\\levan\\AppData\\Local\\Temp\\tmpyu77t0kflibemscripten_js_symbols.so --strip-debug --export=add_record_js --export=print_all_js --export=find_by_name_js --export=delete_by_passengerId_js --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=_emscripten_stack_alloc --export=__wasm_call_ctors --export=_emscripten_stack_restore --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-table -z stack-size=65536 --no-growable-memory --initial-heap=16777216 --no-entry --stack-first --table-base=1
        wasm-ld: error: symbol exported via --export not found: add_record_js
        wasm-ld: error: symbol exported via --export not found: print_all_js
        wasm-ld: error: symbol exported via --export not found: find_by_name_js
        wasm-ld: error: symbol exported via --export not found: delete_by_passengerId_js
        emcc: error: 'D:/NSU/MyLabs/ADDED_LIBS/emsdk/upstream/bin\\wasm-ld.exe -o cmTC_34f99.wasm CMakeFiles/cmTC_34f99.dir/CMakeCCompilerABI.c.obj -LD:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\cache\\sysroot\\lib\\wasm32-emscripten -LD:\\NSU\\MyLabs\\ADDED_LIBS\\emsdk\\upstream\\emscripten\\src\\lib -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc-debug -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\\Users\\levan\\AppData\\Local\\Temp\\tmpyu77t0kflibemscripten_js_symbols.so --strip-debug --export=add_record_js --export=print_all_js --export=find_by_name_js --export=delete_by_passengerId_js --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=_emscripten_stack_alloc --export=__wasm_call_ctors --export=_emscripten_stack_restore --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-table -z stack-size=65536 --no-growable-memory --initial-heap=16777216 --no-entry --stack-first --table-base=1' failed (returned 1)\x0d
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
